#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

 echo "\n" ----------------------------------- "\n" 🚀 Running pre commit commands 🚀 "\n" -----------------------------------
echo "\n"

 echo 🧙 Running lint-staged commands 🧙
yarn lint-staged

 echo "\n"

 echo 🦋 Running pretty-quick command 🦋
yarn pretty-quick --branch main --pattern "**/*.*(js|jsx|ts|tsx)"
